import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../models/news_article.dart';

final rawNewsArticlesProvider = Provider<List<NewsArticle>>((ref) {
  final now = DateTime.now();
  return [
    NewsArticle(
      id: 'news_1',
      title: 'OpenAI Unveils GPT-5 Engine with Multimodal Reasoning Capability',
      summary: 'OpenAI officially announces GPT-5 featuring native reasoning, real-time audio synthesis, and autonomous coding tools designed to assist complex software engineering workflows.',
      imageUrl: 'https://images.unsplash.com/photo-1677442136019-21780efad99a?q=80&w=1000&auto=format&fit=crop',
      category: 'AI',
      author: 'TechCrunch',
      authorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=200&auto=format&fit=crop',
      publishedAt: now.subtract(const Duration(minutes: 25)),
      readTime: '1 min',
      likes: 1420,
      shares: 380,
      commentsCount: 154,
    ),
    NewsArticle(
      id: 'news_2',
      title: 'Apple Announces M4 Ultra Mac Studio for Heavy AI Workloads',
      summary: 'Apple introduces the M4 Ultra Mac Studio with 32 CPU cores and 80 GPU cores, setting new standards in local LLM fine-tuning performance.',
      imageUrl: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?q=80&w=1000&auto=format&fit=crop',
      category: 'Technology',
      author: 'The Verge',
      authorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=200&auto=format&fit=crop',
      publishedAt: now.subtract(const Duration(hours: 1)),
      readTime: '1 min',
      likes: 980,
      shares: 210,
      commentsCount: 89,
    ),
    NewsArticle(
      id: 'news_3',
      title: 'Global Semiconductor Sales Surge 24% Driven by AI Data Center Boom',
      summary: 'Global chip demand surges to unprecedented records as enterprise data centers upgrade infrastructure for generative AI inference and neural network training hardware.',
      imageUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?q=80&w=1000&auto=format&fit=crop',
      category: 'Business',
      author: 'Bloomberg',
      authorAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=200&auto=format&fit=crop',
      publishedAt: now.subtract(const Duration(hours: 2)),
      readTime: '1 min',
      likes: 2150,
      shares: 640,
      commentsCount: 312,
    ),
    NewsArticle(
      id: 'news_4',
      title: 'India Wins T20 World Cup Final in Thrilling Last-Over Finish',
      summary: 'India secures victory against South Africa in a nail-biting final over, lifting the T20 World Cup trophy amidst grand celebrations across the nation.',
      imageUrl: 'https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?q=80&w=1000&auto=format&fit=crop',
      category: 'Cricket',
      author: 'ESPN Cricinfo',
      authorAvatar: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?q=80&w=200&auto=format&fit=crop',
      publishedAt: now.subtract(const Duration(hours: 3)),
      readTime: '1 min',
      likes: 18450,
      shares: 4200,
      commentsCount: 1890,
    ),
    NewsArticle(
      id: 'news_5',
      title: 'SpaceX Starship Successfully Completes Full Orbital Re-entry Test',
      summary: 'SpaceX achieves key aerospace milestone as Starship survives peak atmospheric heating during orbital re-entry and executes precise soft landing touchdown in ocean waters.',
      imageUrl: 'https://images.unsplash.com/photo-1517976487492-5750f3195933?q=80&w=1000&auto=format&fit=crop',
      category: 'Science',
      author: 'Reuters Science',
      authorAvatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?q=80&w=200&auto=format&fit=crop',
      publishedAt: now.subtract(const Duration(hours: 4)),
      readTime: '1 min',
      likes: 3400,
      shares: 920,
      commentsCount: 410,
    ),
    NewsArticle(
      id: 'news_6',
      title: 'Real Madrid Signs Top European Striker on Record 5-Year Deal',
      summary: 'Spanish giants Real Madrid confirm landmark summer transfer signing, reinforcing their attacking squad for upcoming Champions League campaigns under new tactical formation.',
      imageUrl: 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?q=80&w=1000&auto=format&fit=crop',
      category: 'Football',
      author: 'Goal.com',
      authorAvatar: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?q=80&w=200&auto=format&fit=crop',
      publishedAt: now.subtract(const Duration(hours: 5)),
      readTime: '1 min',
      likes: 5670,
      shares: 1120,
      commentsCount: 654,
    ),
    NewsArticle(
      id: 'news_7',
      title: 'Indian Fintech Unicorn Secures \$300M in Series E Funding Round',
      summary: 'Bengaluru-based payments startup valuation climbs to \$6 Billion following strategic investments aimed at scaling cross-border remittances and merchant banking products.',
      imageUrl: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?q=80&w=1000&auto=format&fit=crop',
      category: 'Startup',
      author: 'Inc42 Media',
      authorAvatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?q=80&w=200&auto=format&fit=crop',
      publishedAt: now.subtract(const Duration(hours: 6)),
      readTime: '1 min',
      likes: 890,
      shares: 230,
      commentsCount: 45,
    ),
    NewsArticle(
      id: 'news_8',
      title: 'NVIDIA Hits \$3.5 Trillion Market Cap amid Data Center Demand',
      summary: 'NVIDIA passes tech milestones becoming world\'s most valuable public company as global AI chip sales continue accelerating across cloud provider data centers.',
      imageUrl: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?q=80&w=1000&auto=format&fit=crop',
      category: 'Finance',
      author: 'Wall Street Journal',
      authorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=200&auto=format&fit=crop',
      publishedAt: now.subtract(const Duration(hours: 7)),
      readTime: '1 min',
      likes: 4120,
      shares: 890,
      commentsCount: 380,
    ),
    NewsArticle(
      id: 'news_9',
      title: 'GTA VI Official Gameplay Trailer Breaks YouTube 24-Hour View Record',
      summary: 'Rockstar Games drops groundbreaking 4K gameplay preview of Grand Theft Auto VI, garnering over 120 million views within twenty-four hours of premiere release.',
      imageUrl: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?q=80&w=1000&auto=format&fit=crop',
      category: 'Gaming',
      author: 'IGN Digital',
      authorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=200&auto=format&fit=crop',
      publishedAt: now.subtract(const Duration(hours: 8)),
      readTime: '1 min',
      likes: 12400,
      shares: 3400,
      commentsCount: 1540,
    ),
    NewsArticle(
      id: 'news_10',
      title: 'Breakthrough Cancer mRNA Vaccine Enters Phase 3 Clinical Trials',
      summary: 'Medical researchers initiate global late-stage human trials for personalized cancer vaccines designed to prevent tumor recurrence using targeted messenger RNA platform.',
      imageUrl: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?q=80&w=1000&auto=format&fit=crop',
      category: 'Health',
      author: 'Medical News Today',
      authorAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=200&auto=format&fit=crop',
      publishedAt: now.subtract(const Duration(hours: 9)),
      readTime: '1 min',
      likes: 3100,
      shares: 750,
      commentsCount: 210,
    ),
    NewsArticle(
      id: 'news_11',
      title: 'Christopher Nolan\'s Next Sci-Fi Epic Set for IMAX Summer Release',
      summary: 'Warner Bros reveals details on Nolan\'s next theatrical feature film shot entirely on custom 70mm IMAX cameras featuring an all-star ensemble cast.',
      imageUrl: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?q=80&w=1000&auto=format&fit=crop',
      category: 'Movies',
      author: 'Variety Entertainment',
      authorAvatar: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?q=80&w=200&auto=format&fit=crop',
      publishedAt: now.subtract(const Duration(hours: 10)),
      readTime: '1 min',
      likes: 6200,
      shares: 1450,
      commentsCount: 520,
    ),
    NewsArticle(
      id: 'news_12',
      title: 'Global Climate Summit Reaches Accord on Clean Hydrogen Transition',
      summary: 'Delegates from 140 nations sign multilateral treaty committing to clean green hydrogen subsidies and phasing out industrial carbon emissions by 2040.',
      imageUrl: 'https://images.unsplash.com/photo-1466611653911-95081537e5b7?q=80&w=1000&auto=format&fit=crop',
      category: 'World',
      author: 'BBC World News',
      authorAvatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?q=80&w=200&auto=format&fit=crop',
      publishedAt: now.subtract(const Duration(hours: 11)),
      readTime: '1 min',
      likes: 1890,
      shares: 430,
      commentsCount: 165,
    ),
    NewsArticle(
      id: 'news_13',
      title: 'India Unveils High-Speed Bullet Train Route Connecting Key Metros',
      summary: 'Indian Railways completes inaugural test run on the new high-speed rail corridor operating at 320 km/h, cutting transit times dramatically across industrial hubs.',
      imageUrl: 'https://images.unsplash.com/photo-1532105956626-9569c03602f6?q=80&w=1000&auto=format&fit=crop',
      category: 'India',
      author: 'NDTV Press',
      authorAvatar: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?q=80&w=200&auto=format&fit=crop',
      publishedAt: now.subtract(const Duration(hours: 12)),
      readTime: '1 min',
      likes: 7420,
      shares: 1980,
      commentsCount: 840,
    ),
    NewsArticle(
      id: 'news_14',
      title: 'IIT & Stanford Announce Joint AI and Robotics Fellowship Program',
      summary: 'Top institutes partner to offer fully funded doctoral research grants targeting humanoid robotics, autonomous drone navigation, and ethical artificial intelligence systems.',
      imageUrl: 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?q=80&w=1000&auto=format&fit=crop',
      category: 'Education',
      author: 'EdTech Journal',
      authorAvatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?q=80&w=200&auto=format&fit=crop',
      publishedAt: now.subtract(const Duration(hours: 14)),
      readTime: '1 min',
      likes: 2950,
      shares: 610,
      commentsCount: 130,
    ),
    NewsArticle(
      id: 'news_15',
      title: 'Quantum Computing Startup Achieves 10,000 Logical Qubit Benchmark',
      summary: 'Physicists demonstrate error-corrected quantum computation achieving unprecedented stability required for complex molecular simulation and cryptography applications.',
      imageUrl: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?q=80&w=1000&auto=format&fit=crop',
      category: 'AI',
      author: 'MIT Technology Review',
      authorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=200&auto=format&fit=crop',
      publishedAt: now.subtract(const Duration(hours: 16)),
      readTime: '1 min',
      likes: 3890,
      shares: 940,
      commentsCount: 275,
    ),
    NewsArticle(
      id: 'news_16',
      title: 'Tesla Robotaxi Fleet Officially Launches Commercial Rides in Austin',
      summary: 'Tesla begins public autonomous ride-hailing services using vision-only Full Self-Driving hardware without safety drivers present behind steering wheel.',
      imageUrl: 'https://images.unsplash.com/photo-1563720223185-11003d516935?q=80&w=1000&auto=format&fit=crop',
      category: 'Technology',
      author: 'Electrek',
      authorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=200&auto=format&fit=crop',
      publishedAt: now.subtract(const Duration(hours: 18)),
      readTime: '1 min',
      likes: 8300,
      shares: 2100,
      commentsCount: 1120,
    ),
    NewsArticle(
      id: 'news_17',
      title: 'Billionaire Tech Founder Pledges \$1B toward Fusion Energy Research',
      summary: 'Philanthropic venture capital fund allocates emergency grants to magnet containment startups seeking net positive nuclear fusion power plant commercialization.',
      imageUrl: 'https://images.unsplash.com/photo-1507413245164-6160d8298b31?q=80&w=1000&auto=format&fit=crop',
      category: 'Science',
      author: 'Forbes Global',
      authorAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=200&auto=format&fit=crop',
      publishedAt: now.subtract(const Duration(hours: 20)),
      readTime: '1 min',
      likes: 2450,
      shares: 510,
      commentsCount: 185,
    ),
    NewsArticle(
      id: 'news_18',
      title: 'Premier League Agrees Historic Multi-Billion Streaming Broadcast Rights',
      summary: 'English Football Association signs record streaming deal ensuring global live coverage across mobile apps and smart TVs starting next football season.',
      imageUrl: 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?q=80&w=1000&auto=format&fit=crop',
      category: 'Sports',
      author: 'Sky Sports',
      authorAvatar: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?q=80&w=200&auto=format&fit=crop',
      publishedAt: now.subtract(const Duration(hours: 22)),
      readTime: '1 min',
      likes: 4900,
      shares: 1100,
      commentsCount: 420,
    ),
    NewsArticle(
      id: 'news_19',
      title: 'Space Agency Discovers Water Ice Deposits in Lunar South Pole Crater',
      summary: 'Orbital spectrographs confirm thick surface water ice layers within permanently shadowed craters, clearing path for permanent manned Moon base habitats.',
      imageUrl: 'https://images.unsplash.com/photo-1614728894747-a83421e2b9c9?q=80&w=1000&auto=format&fit=crop',
      category: 'Science',
      author: 'NASA Newsroom',
      authorAvatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?q=80&w=200&auto=format&fit=crop',
      publishedAt: now.subtract(const Duration(days: 1)),
      readTime: '1 min',
      likes: 9100,
      shares: 2800,
      commentsCount: 930,
    ),
    NewsArticle(
      id: 'news_20',
      title: 'Central Banks Announce Interoperable Digital Currency Settlement Network',
      summary: 'Monetary consortium launches cross-border settlement rails utilizing cryptographic verification to settle multi-billion dollar international trade instantly with minimal transaction fees.',
      imageUrl: 'https://images.unsplash.com/photo-1621416894569-0f39ed31d247?q=80&w=1000&auto=format&fit=crop',
      category: 'Finance',
      author: 'Financial Times',
      authorAvatar: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?q=80&w=200&auto=format&fit=crop',
      publishedAt: now.subtract(const Duration(days: 1, hours: 2)),
      readTime: '1 min',
      likes: 3120,
      shares: 670,
      commentsCount: 290,
    ),
  ];
});

final selectedCategoryProvider = StateProvider<String>((ref) => 'All');

final filteredNewsProvider = Provider<List<NewsArticle>>((ref) {
  final articles = ref.watch(rawNewsArticlesProvider);
  final category = ref.watch(selectedCategoryProvider);
  
  if (category == 'All') return articles;
  return articles.where((a) => a.category == category).toList();
});
