-- Phase 3 MySQL Schema Expansion for AI News Engine
USE newsx_db;

ALTER TABLE news_articles
ADD COLUMN IF NOT EXISTS summary_mr TEXT DEFAULT NULL,
ADD COLUMN IF NOT EXISTS summary_hi TEXT DEFAULT NULL,
ADD COLUMN IF NOT EXISTS category_ai VARCHAR(50) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS tags JSON DEFAULT NULL,
ADD COLUMN IF NOT EXISTS keywords JSON DEFAULT NULL,
ADD COLUMN IF NOT EXISTS sentiment VARCHAR(20) DEFAULT 'Neutral',
ADD COLUMN IF NOT EXISTS importance_score INT DEFAULT 5,
ADD COLUMN IF NOT EXISTS why_it_matters TEXT DEFAULT NULL,
ADD COLUMN IF NOT EXISTS related_topics JSON DEFAULT NULL,
ADD COLUMN IF NOT EXISTS source_name VARCHAR(100) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS canonical_url TEXT DEFAULT NULL,
ADD COLUMN IF NOT EXISTS status ENUM('pending', 'processed', 'failed') DEFAULT 'pending',
ADD COLUMN IF NOT EXISTS processed_at TIMESTAMP NULL DEFAULT NULL,
ADD COLUMN IF NOT EXISTS trending_score FLOAT DEFAULT 0.0;
